---
title: "Milestone 3"
author: "Hannah Valencia"
date: "2/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 delimit ;
set more 1;
set matsize 800;
capture log close;
log using replication_science.log, replace;
clear;

**********************;
* Replicate Figure 1 *;
**********************;
* The data are in an Excel spreadsheet that is provided in dataverse;

**********************;
* Replicate Figure 2 *;
**********************;

*First, create sales figures *;
******************************;

<!-- The use command is similar to a read.(file type) in R.  -->
<!-- Here we are using the bckcheck-state-public.dta file. -->

use bckcheck-state-public.dta;

<!-- Keep if is similar to filter and only keeps the data where the year is 2008 or later. -->

keep if year>=2008;

<!-- The collapse command makes a dataset of summary statistics. -->
<!-- The "(sum) total" tells which statistic is being calculated. I believe this means that here we are taking the sum of the "total" column. -->
<!-- The by(year month) groups over which statistic is to be calculated. -->

collapse (sum) total, by(year month);

<!-- The generate command is the same as mutate in R. -->
<!-- This is generating columns titled "sandyhookp[#]" which I believe is grouping the data into periods in relation to the Sandy Hook shooting. -->
<!-- The shooting took place in December of 2012, so the first period is data that is from December 2012. -->
<!-- The second period is January of 2013, the third period is February of 2013, the fourth period is March of 2013, and the fifth period is April of 2013. -->

gen sandyhookp1 = year == 2012 & month == 12;
gen sandyhookp2 = year == 2013 & month == 1;
gen sandyhookp3 = year == 2013 & month == 2;
gen sandyhookp4 = year == 2013 & month == 3;
gen sandyhookp5 = year == 2013 & month == 4;

<!-- The tabulate command, or just tab, creates tables of frequencies. This command is similar to summary. -->
<!-- Here we are getting the summary statistics for the month variable. -->
<!-- They then generate a column titled monthdv that uses a formula similar to a for loop in R. -->
<!-- I am not exactly sure what this loop is calculating but it is testing consecuatively over the years 2009 to 2015. -->

tab month, gen(monthdv);
forvalues y = 2009/2015 {;
  gen yrdv`y' = year == `y';
};

*Estimate de-seasonalized and de-trended gun sales;

<!-- The regress command runs a regression with the first variable as the y and all the following variables as the x's. -->
<!-- Here we regress the periods, monthdv's, and yrdv's on total. -->
<!-- They then predict the residuals. -->

regress total sandyhookp1-sandyhookp5 monthdv2-monthdv12 yrdv2009-yrdv2015;
predict resid, resid;

<!-- They format the total. I am not completely sure what this exact format is, but it might be 3 digits with only one decimal. -->

format total %10.0f;
*These residuals are the points for the times series in Figure 2.;
*The points for the Sandy Hook time period are the residuals + the coefficients on sandyhookp1-sandyhookp5.;
list year month total resid, clean;
clear;

* Next, create mortality bars *;
*******************************;

<!-- The use command in Stata is to import data, similar to a read.(file type) in R. -->
<!-- Here they are using the data "deaths-age-public.dta" file that they have imported. -->

use deaths-age-public.dta;

<!-- The keep if function is similar to filtering, where it goes through the data and only keeps the data that meets the given criteria. -->
<!-- Here they are filtering the data for the age category 0-14.  -->

keep if agecat=="0_14";

<!-- They use the keep if function again to filter for the 12th month or months less than or equal to 4. -->
<!-- Using common sense, I am assuming, this would be filtering for January-April and December. -->

keep if month==12 | month<=4;

<!-- The "gen" or generate function is like using mutate in R. -->
<!-- Here we are generating a mortality rate column by dividing the number of deaths by the population for each age group and multiplying by 100,000. -->
<!-- The multiplying by 100,000 I believe puts the mortality rate into a percentage per capita, although I am unsure.  -->

gen mortrate = (numdeaths/pop_byage)*100000;

<!-- Here the authors of this code confirm that they are looking strictly at the December-April data. -->
<!-- They are grouping the December data with the four months of the following year, but classifying it all as the later year. -->

* We use five-month December-April windows, with the year for each window defined as the later of the two years;

<!-- Here they reclassify the December data to the following year. -->
<!-- They use replace if to add 1 to the year that December is classified under to the following year. -->
<!-- Even though it is not December of the year that they are reclassifying it to, it is the month adjacent to the other range of months so they group it all together. -->

replace year = year+1 if month==12;

<!-- The tabulate command, or just tab, creates tables of frequencies. This command is similar to summary. -->
<!-- Here we are getting the summary statistics for the year variable. -->
<!-- The drop if is the opposite of keep if, and similar to filter when you filter to get rid of something. -->
<!-- Here we are filtering out all data for years before 2008 and after 2015, leaving us only with data between and including those years. -->

tab year;
drop if year<2008 | year>2015;

<!-- Again we use the generate command to create a new column titled "trend" that takes the year the data is from and subtracts 2007, making 2007 a base year, setting 2008 to year 1, and so on. -->
<!-- We generate a second new column that takes this value and squares it. -->
<!-- I am not totally sure why we are looking at the square of the trend year, possibly for equations that will be used later on. -->

gen trend = year-2007;
gen trend2 = trend^2;

<!-- Since this paper is looking at trends before and after the Sandy Hook shooting, we do not want to include the year of the Sandy Hook shooting (2013). -->
<!-- The regress command runs a regression, here looking at the effect of trend and trend2 (the x, or independent, variables) on mortality rate (the y, or dependent, variable). -->
<!-- The "if year ~= 2013" tells the program to not regress when the year is 2013, with the tilde being the indicator of the negation. -->


*We exclude the Sandy Hook window from our estimation of the trend;
regress mortrate trend trend2 if year ~= 2013;
predict resid, resid;

sort year;
collapse (sum) numdeaths mortrate resid, by(year);

list, clean;
clear;

**********************;
* Replicate Figure 3 *;
**********************;

use bckcheck-state-public.dta;

sort year stfips;
merge year stfips using population-state-public.dta;
tab _merge;

keep if year>=2008;

*Calculate sales per 100,000;
gen totalpc = (total/pop)*100000;

gen sandyhook = (year == 2012 & month == 12)|(year==2013 & month<=4);

tab month, gen(monthdv);
forvalues y = 2009/2015 {;
  gen yrdv`y' = year == `y';
};

foreach x in AK AL AR AZ CA CO CT DE FL GA HI IA ID IL IN KS LA MA MD ME MI MN MO MS MT ND NE NH NJ NM NV NY OH OK OR PA RI SC SD TN TX  VA VT WA WI WV WY {;

*Estimate de-seasonalized and de-trended gun sales;
*Multiply coefficients from these regressions by 5 to obtain values reported in Figure 3;
di "`x'";
regress totalpc sandyhook monthdv2-monthdv12 yrdv2009-yrdv2015 if stname=="`x'";
};
clear;

************************;
* Replication Figure 4 *;
************************;

use deaths-age-state-NOTPUBLIC.dta;
sort stfips year month;

sort stfips year month;
merge m:1 stfips year month using bckcheck-state-public.dta;
tab _merge;
drop if _merge ~= 3;
drop _merge;

sort stfips year agecat;
merge stfips year agecat using population-state-age-public;
tab _merge;
drop if _merge~=3;

keep if agecat == "0_14";
keep if month <= 4 | month == 12;
     replace year = year + 1 if month == 12;
drop if year < 2008 | year > 2015;

* drop states with clearly flawed gun sales data (DC, KY, NC, and UT);
drop if stfips == 11 | stfips == 21 | stfips == 37 | stfips == 49;

sort stfips year;

gen mortrate = (numdeaths/pop_byage)*100000;

collapse (mean) mortrate pop_byage, by(stfips year);

gen largeinc = stfips == 33 | stfips == 2 | stfips == 30 | stfips == 46 |	
    stfips == 56 | stfips == 54 | stfips == 40 | stfips == 29 |
	stfips == 38 | stfips == 16 | stfips == 27 | stfips == 47 | 
	stfips == 53 | stfips == 20 | stfips == 55 | stfips == 42 |
	stfips ==  5 | stfips == 31 | stfips == 28 | stfips == 22 |
	stfips == 41 | stfips ==  8	| stfips == 23 | stfips == 17 |
	stfips == 39 | stfips == 51 | stfips == 50 | stfips == 35 |
	stfips == 48 | stfips == 32 | stfips == 45;

tab largeinc;
sort stfips year;

sort largeinc year;
collapse (mean) mortrate [weight=pop_byage], by(largeinc year);

gen trend = year - 2007;
gen trend2 = trend^2;

regress mortrate trend trend2 if year ~= 2013 & largeinc == 1;
predict residbig, residual;
regress mortrate trend trend2 if year ~= 2013 & largeinc == 0;
predict residsml, residual;

sort largeinc year;
list year mortrate residbig largeinc if largeinc == 1, clean;
list year mortrate residsml largeinc if largeinc == 0, clean;
clear;

*********************************************************;
* Replication Table 1, Panel 1 (Descriptive Statistics) *;
*********************************************************;
use deaths-age-public.dta;
keep if year==2013;
keep if causedeath=="acc_firearms";

format pop_byage %10.0f;

*Multiply number of deaths by 5 to obtain average number of deaths in a 5-month window;
bysort agecat: summ numdeaths pop_byage;
clear;

*****************************;
*Replicate Table 1, panel 2 *;
*****************************;

use deaths-age-public.dta;

keep if year>=2008;

gen sandyhook=(year==2012 & month==12)|(year==2013 & month<=4);

collapse (sum) numdeaths pop_byage, by(year month agecat sandyhook);

gen mortrate=(numdeaths/pop_byage)*100000;

foreach x in 0_14 15p {;
di "`x'";
xi: regress mortrate i.month i.year sandyhook if agecat=="`x'";
};

collapse (sum) numdeaths pop_byage, by(year month sandyhook);

gen mortrate=(numdeaths/pop_byage)*100000;
summ mortrate;
xi: regress mortrate i.month i.year sandyhook;
clear;

*****************************;
*Replicate Table 1, panel 3 *;
*****************************;

use deaths-age-public.dta;

keep if year>=2008;

*Create total population variable that varies by year, but not by age;
egen pop=sum(pop_byage), by(year month);

sort year month;
merge year month using bckcheck-public.dta;
tab _merge;

*Calculate background checks per 100 population (which is the same as 1000s of background checks per 100,000);
gen totalpc=(total/pop)*100;

*Create sandyhook instruments;
gen sandyhook=(year==2012 & month==12)|(year==2013 & month<=4);

*Calculate mortality rate per 100,000;
gen mortrate=(numdeaths/pop_byage)*100000;

foreach x in 0_14 15p {;
di "`x'";
xi: ivregress 2sls mortrate i.month i.year (totalpc = sandyhook) if agecat=="`x'";
};

*Collapse to full population;
collapse (sum) numdeaths pop_byage, by(year month totalpc sandyhook);

*Calculate mortality rate for full population;
gen mortrate=(numdeaths/pop_byage)*100000;

xi: ivregress 2sls mortrate i.month i.year (totalpc=sandyhook);
clear;

************************************************************;
*Replicate Table 1, Panel 4                                *;
*The data for these regressions are not publicly available *;
************************************************************;

use deaths-age-state-NOTPUBLIC.dta;

keep if year>=2008;

sort stfips year agecat;
merge stfips year agecat using population-state-age-public.dta;
tab _merge;
keep if _merge==3; 
capture drop _merge;

sort stfips year month;
merge stfips year month using bckcheck-state-public.dta;
tab _merge;
keep if _merge==3;

*Exclude states with clearly flawed gun sales data (DC, KY NC, and UT);
drop if stfips==11|stfips==21|stfips==37|stfips==49;

*Create sandyhook instruments;
gen sandyhook=(year==2012 & month==12)|(year==2013 & month<=4);
gen shook_obama=sandyhook*pctobama;

gen stmonth=(stfips*100)+month;

*Create total population variable that varies by year, but not by age;
egen pop=sum(pop_byage), by(stfips year month);

*Calculate background checks per 100 population (which is the same as 1000s of background checks per 100,000);
gen totalpc=(total/pop)*100;

*Calculate mortality rate per 100,000;
gen mortrate=(numdeaths/pop_byage)*100000;

foreach x in 0_14 15p {;
xi: ivreg2 mortrate i.month i.stname*i.year i.stname*i.month (totalpc = sandyhook shook_obama) if agecat=="`x'" [weight=pop_byage], cluster(stname);
};

*Collapse to full-population;
collapse (sum) numdeaths, by(stfips stname year month total pop totalpc sandyhook shook_obama);

*Calculate mortality rate for full population;
gen mortrate=(numdeaths/pop)*100000;

xi: ivreg2 mortrate i.month i.stname*i.year i.stname*i.month (totalpc = sandyhook shook_obama) [weight=pop], cluster(stname);
clear;
